baseURL = "/doxrblogs/"
theme = "hugo-blog-awesome"

[params]
    description = "A security research blog, by an intelligent adonis."
    showDarkMode = true
    [params.author]
        name = "doxr"

[markup]
  [markup.highlight]
    style = "monokai"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 2

[Languages]
  [Languages.en]
  title = "Doxr's Security Research"
    languageCode = "en"
    defaultContentLanguage = "en"

    [Languages.en.params]
      description = "A security research blog, by an intelligent adonis."
      defaultColor = "dark"
      dateFormat = "2 Jan 2006"
      rssFeedDescription = "summary"

      [Languages.en.params.author]
        intro = "Doxr's Security Research"
        name = "doxr"
        description = "A security research blog, by an intelligent adonis."